### ISSUE TITLE
Tried cutechess build on Linux Ubuntu eoan, halt at Creating qmake...

### ISSUE THREAD

**Issue by abdulbadii** [glinscott/fishtest#520]
I tried cutechess build, it's successful all up to configure:

```
Creating qmake...
.................................../usr/src/qt5/qtbase/src/corelib/global/qrandom.cpp: In static member function ‘static void 

QRandomGenerator::SystemAndGlobalGenerators::securelySeed(QRandomGenerator*)’:
/usr/src/qt5/qtbase/src/corelib/global/qrandom.cpp:457:62: error: no matching function for call to ‘std::mersenne_twister_engine<unsigned int, 32, 624, 397, 31, 2567483615, 11, 4294967295, 7, 2636928640, 15, 4022730752, 18, 1812433253>::mersenne_twister_engine(QRandomGenerator::SystemGenerator&)’
  457 |         new (&rng->storage.engine()) RandomEngine(self()->sys);
      |                                                              ^
In file included from /usr/include/c++/9/random:49,
                 from /usr/src/qt5/qtbase/src/corelib/global/qrandom.h:45,
                 from /usr/src/qt5/qtbase/src/corelib/global/qrandom.cpp:43

```

What's actually caused the failure ?

**Comment by ppigazzini** [comment]
What version of Ubuntu are you using?
Please remember that the wiki script requires Ubuntu 14.04.

**Comment by abdulbadii** [comment]
```
$  lsb_release -a
LSB Version:	core-11.0.1ubuntu1-noarch:security-11.0.1ubuntu1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan

```
as said early on title: eoan   ..is the latest

**Comment by ppigazzini** [comment]
I suggest to install lxd/lxc and build on Ubuntu 14.04 using these instructions https://github.com/glinscott/fishtest/issues/506#issuecomment-574140535

**Comment by ppigazzini** [comment]
By the way if you need only cutechess-cli you can use the fishtest build 
https://github.com/official-stockfish/books

**Comment by ppigazzini** [comment]
@abdulbadii I'm closing this issue.
The fishtest worker downloads a well tested cutechess-cli from the SF repo, so the cutechess-cli wiki page targets principally the fishtest/SF maintainers (and we routinely build cutechess with virtual machine/linux container based on Ubuntu 14.04).

You should ask for support to the QT project.
